### ISSUE TITLE
Bikeshare_ie not working anymore

### ISSUE THREAD

**Issue by Altonss** [eskerda/pybikes#452]
I noticed today that all systems using Bikeshare_ie are not working anymore since 22 days.

**Comment by Altonss** [comment]
Here is the error I get:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/username/.local/lib/python2.7/site-packages/pybikes/bikeshare_ie.py", line 37, in update
    data = json.loads(stations_html[0])
IndexError: list index out of range
`
